<a href="https://colab.research.google.com/github/ciepielajan/NLP_Text-Summarization/blob/main/%232_Text_Summarization_gensim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 #2_Text_Summarization_gensim.ipynb

In [ ]:
from gensim.summarization import summarize

In [ ]:
print(summarize(text))

Ferrari (/fəˈrɑːri/; Italian: [ferˈraːri]) is an Italian luxury sports car manufacturer based in Maranello, Italy.Founded by Enzo Ferrari in 1939 out of the Alfa Romeo race division as Auto Avio Costruzioni, the company built its first car in 1940.
In 1933, Alfa Romeo withdrew its in-house racing team and Scuderia Ferrari took over as its works team:[1]the Scuderia received Alfa's Grand Prix cars of the latest specifications and fielded many famous drivers such as Tazio Nuvolari and Achille Varzi.In 1938, Alfa Romeo brought its racing operation again in-house, forming Alfa Corse in Milan and hired Enzo Ferrari as manager of the new racing department; therefore the Scuderia Ferrari was disbanded.[1]In September 1939, Ferrari left Alfa Romeo under the provision he would not use the Ferrari name in association with races or racing cars for at least four years.[1] A few days later he founded Auto Avio Costruzioni, headquartered in the facilities of the old Scuderia Ferrari.[1]The new compa

In [ ]:
print(summarize(text, split=True))

['Ferrari (/fəˈrɑːri/; Italian: [ferˈraːri]) is an Italian luxury sports car manufacturer based in Maranello, Italy.Founded by Enzo Ferrari in 1939 out of the Alfa Romeo race division as Auto Avio Costruzioni, the company built its first car in 1940.', "In 1933, Alfa Romeo withdrew its in-house racing team and Scuderia Ferrari took over as its works team:[1]the Scuderia received Alfa's Grand Prix cars of the latest specifications and fielded many famous drivers such as Tazio Nuvolari and Achille Varzi.In 1938, Alfa Romeo brought its racing operation again in-house, forming Alfa Corse in Milan and hired Enzo Ferrari as manager of the new racing department; therefore the Scuderia Ferrari was disbanded.[1]In September 1939, Ferrari left Alfa Romeo under the provision he would not use the Ferrari name in association with races or racing cars for at least four years.[1] A few days later he founded Auto Avio Costruzioni, headquartered in the facilities of the old Scuderia Ferrari.[1]The new 

In [ ]:
print(summarize(text, ratio=0.5))

Ferrari (/fəˈrɑːri/; Italian: [ferˈraːri]) is an Italian luxury sports car manufacturer based in Maranello, Italy.Founded by Enzo Ferrari in 1939 out of the Alfa Romeo race division as Auto Avio Costruzioni, the company built its first car in 1940.
However, the company's inception as an auto manufacturer is usually recognized as 1947, when the first Ferrari-badged car was completedEnzo Ferrari was not initially interested in the idea of producing road cars when he formed Scuderia Ferrari in 1929, with headquarters in Modena.
In 1933, Alfa Romeo withdrew its in-house racing team and Scuderia Ferrari took over as its works team:[1]the Scuderia received Alfa's Grand Prix cars of the latest specifications and fielded many famous drivers such as Tazio Nuvolari and Achille Varzi.In 1938, Alfa Romeo brought its racing operation again in-house, forming Alfa Corse in Milan and hired Enzo Ferrari as manager of the new racing department; therefore the Scuderia Ferrari was disbanded.[1]In Septembe

In [ ]:
print(summarize(text, word_count=100))

In 1933, Alfa Romeo withdrew its in-house racing team and Scuderia Ferrari took over as its works team:[1]the Scuderia received Alfa's Grand Prix cars of the latest specifications and fielded many famous drivers such as Tazio Nuvolari and Achille Varzi.In 1938, Alfa Romeo brought its racing operation again in-house, forming Alfa Corse in Milan and hired Enzo Ferrari as manager of the new racing department; therefore the Scuderia Ferrari was disbanded.[1]In September 1939, Ferrari left Alfa Romeo under the provision he would not use the Ferrari name in association with races or racing cars for at least four years.[1] A few days later he founded Auto Avio Costruzioni, headquartered in the facilities of the old Scuderia Ferrari.[1]The new company ostensibly produced machine tools and aircraft accessories.


In [ ]:
from gensim.summarization import keywords
print(keywords(text))

ferrari
racing
races
cars
romeo race
car manufacturer
alfa
scuderia
fiat
enzo
drivers
marchionne
team
teams
new
factory
company
manufacturers
producing
produced
circuit
little
public
initially
initial
days
works
work
auto
million
resigned
amedeo
louis
member
result
group resulting
investment
spa
italian
model


In [ ]:
def pagerank(sim_mat, eps=0.0001, d=0.85,iter=100):
    prob = np.ones(len(sim_mat)) / len(sim_mat)
    count =0
    while True:
        new_prob  = np.ones(len(sim_mat)) * (1 - d) / len(sim_mat) + (d * sim_mat.T.dot(prob))
        delta = abs(new_prob - prob).sum()
        if delta <= eps:
            return new_prob
        prob = new_prob
    return prob


In [ ]:
import numpy as np


In [ ]:
sim_mat= np.zeros([4,4])

sim_mat[1,0] = sim_mat[0,1] = 0.2
sim_mat[2,0] = sim_mat[0,2] = 0.1
sim_mat[3,0] = sim_mat[0,3] = 0.4
sim_mat[1,2] = sim_mat[2,1] = 0.1
sim_mat[2,1] = sim_mat[2,1] = 0.1
sim_mat[3,1] = sim_mat[1,3] = 0.2
sim_mat[2,3] = sim_mat[3,2] = 0.4
print(sim_mat)

[[0.  0.2 0.1 0.4]
 [0.2 0.  0.1 0.2]
 [0.1 0.1 0.  0.4]
 [0.4 0.2 0.4 0. ]]


In [ ]:
prob = pagerank(sim_mat)


In [ ]:
print(prob)

[0.09894556 0.0820077  0.09252005 0.11655406]


In [ ]:
ranked_sentence_indexes = [item[0] for item in sorted(enumerate(prob), key=lambda item: -item[1])]
print(ranked_sentence_indexes)

[3, 0, 2, 1]
